create table if not exists verifications (
  id bigint generated by default as identity primary key,

  inquiry_id text unique not null,

  reference_id text,

  user_id text not null,

  status text default 'created',

  verification_status text,

  webhook_data jsonb,

  persona_account_id text,

  template_id text,

  redirect_uri text,

  failure_reasons jsonb default '[]'::jsonb,

  latest_failure_reasons jsonb default '[]'::jsonb,

  remaining_attempts integer default 3,

  created_at timestamp with time zone default timezone('utc'::text, now()),

  updated_at timestamp with time zone default timezone('utc'::text, now())
);



create index if not exists idx_verifications_id 
on verifications(id);


create index if not exists idx_verifications_inquiry_id 
on verifications(inquiry_id);


create index if not exists idx_verifications_reference_id 
on verifications(reference_id);


create index if not exists idx_verifications_user_id 
on verifications(user_id);


create index if not exists idx_verifications_template_id 
on verifications(template_id);


create index if not exists idx_verifications_persona_account_id 
on verifications(persona_account_id);


create index if not exists idx_verifications_created_at 
on verifications(created_at);